resume_training: false
from_start: false

epochs: 100
batch_size: 32
lr: 0.0001
num_workers: 4
num_gpus: 4

grad_accum_every: 1
ema_update_every: 10
max_grad_norm: 1.0

val_every_epoch: 1
save_every_epoch: 5
log_every_step: 50

use_wandb_tracking: true
wandb_project_name: BSPLINE_VAE_V1
wandb_run_name: train_1108_bspline_1_meta_after_fuser_wo_attn_mults_dim_64

data:
    train_json_dir: ../data/logan_bspline/0/0000
    val_json_dir: ../data/logan_bspline_test/0009
    max_num_surfaces: 500

model:
    mults_dim: 64
    checkpoint_folder: checkpoints/train_1108_bspline_1_meta_after_fuser_wo_attn_mults_dim_64
    checkpoint_file_name: model.pt 0


loss:
    recon_weight: 1.0
    cls_weight: 1.0
    kl_weight: 0
    kl_annealing_steps: 20000  # Number of steps to anneal KL weight from 0 to kl_weight
    kl_free_bits: 0.25  # Free bits per latent dimension (in nats)