resume_training: true
from_start: false

epochs: 100
batch_size: 32
lr: 0.0001
num_workers: 4
num_gpus: 4

grad_accum_every: 1
ema_update_every: 10
max_grad_norm: 1.0

val_every_epoch: 1
save_every_epoch: 5
log_every_step: 50

use_wandb_tracking: true
wandb_project_name: BSPLINE_VAE_V1
wandb_run_name: train_1108_bspline_1_meta_after_fuser_wo_attn_mults_dim_64

data:
    train_file: ./assets/all_bspline_paths.txt
    train_num: -1
    val_file: ./assets/all_bspline_paths_test.txt
    val_num: -1

model:
    mults_dim: 64
    checkpoint_folder: checkpoints/train_1108_bspline_1_meta_after_fuser_wo_attn_mults_dim_64
    checkpoint_file_name: model-20.pt


loss:
    recon_weight: 1.0
    cls_weight: 1.0
    kl_weight: 0
    kl_annealing_steps: 20000  # Number of steps to anneal KL weight from 0 to kl_weight
    kl_free_bits: 0.25  # Free bits per latent dimension (in nats)